Repository PennyLaneAI/pennylane-lightning, pull requests merged in 2024-11, with the labels that each got.

#971 Fix qml.state() support for LT
  .github/CHANGELOG.md
  doc/lightning_tensor/device.rst
  tests/test_gates.py
Labels: bug-fix, do not merge, urgent, ci:use-gpu-runner

#981 Merge v0.39.0_rc to master
  .github/CHANGELOG.md
  .github/workflows/compat-docker-release.yml
  .github/workflows/tests_gpu_python.yml
  .github/workflows/tests_lkcpu_python.yml
  .github/workflows/wheel_macos_arm64.yml
  .github/workflows/wheel_macos_x86_64.yml
  README.rst
  cmake/support_catalyst.cmake
  doc/lightning_tensor/device.rst
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/lightning_base.py
  pennylane_lightning/core/src/simulators/lightning_gpu/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_gpu/catalyst/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_gpu/catalyst/LightningGPUObsManager.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/catalyst/LightningGPUSimulator.cpp
  pennylane_lightning/core/src/simulators/lightning_gpu/catalyst/LightningGPUSimulator.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/catalyst/tests/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_gpu/catalyst/tests/Test_LightningGPUGradient.cpp
  pennylane_lightning/core/src/simulators/lightning_gpu/catalyst/tests/Test_LightningGPUMeasures.cpp
  pennylane_lightning/core/src/simulators/lightning_gpu/catalyst/tests/Test_LightningGPUSimulator.cpp
  pennylane_lightning/core/src/simulators/lightning_gpu/catalyst/tests/runner_lightning_gpu_catalyst.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/CMakeLists.txt
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_gpu/lightning_gpu.toml
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  requirements-dev.txt
  requirements-tests.txt
  scripts/create_lightning_rc.sh
  setup.py
  tests/test_device.py
  tests/test_gates.py
Labels: urgent

#982 Fix PTM stable latest. Removing FIXME patch for 0.39
  .github/CHANGELOG.md
  .github/workflows/tests_lgpumpi_python.yml
  .github/workflows/tests_lkcpu_python.yml
  .github/workflows/tests_lkcuda_python.yml
  .github/workflows/tests_lqcpu_python.yml
  pennylane_lightning/core/_version.py
Labels: urgent

#984 Fix pennylane dependency rc to master v0.39 release
  .github/CHANGELOG.md
  requirements-dev.txt
  requirements-tests.txt
Labels: urgent

#942 Update lightning_kokkos_catalyst CUDA target to work with Catalyst
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/LightningKokkosSimulator.hpp
Labels: urgent, ci:use-gpu-runner

#959 Unify gate memory layout for lgpu and ltensor
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_gpu/StateVectorCudaMPI.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/StateVectorCudaManaged.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/gates/tests/Test_StateVectorCudaManaged_Generators.cpp
  pennylane_lightning/core/src/utils/cuda_utils/cuGates_host.hpp
Labels: ci:use-multi-gpu-runner, urgent, ci:use-gpu-runner

#970 LGPU add controlled adjoint support
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/algorithms/tests/Test_AdjointJacobian.cpp
  pennylane_lightning/core/src/simulators/lightning_gpu/StateVectorCudaManaged.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/algorithms/AdjointJacobianGPU.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/algorithms/tests/Test_AdjointJacobianGPU.cpp
  pennylane_lightning/core/src/simulators/lightning_gpu/gates/tests/Test_StateVectorCudaManaged_Generators.cpp
  pennylane_lightning/core/src/simulators/lightning_gpu/utils/cuStateVec_helpers.hpp
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  tests/test_adjoint_jacobian.py
Labels: ci:build_wheels, urgent, ci:use-gpu-runner

#952 (LK-C-1) Add controlled 1-qubit named-gate (e.g. NCPauliX) support to Lightning Kokkos
  pennylane_lightning/core/src/simulators/lightning_kokkos/StateVectorKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/bindings/LKokkosBindings.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/LightningKokkosSimulator.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/BasicGateFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/BasicGeneratorFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/MatrixGateFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/tests/Test_StateVectorKokkos_NonParam.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/tests/Test_StateVectorKokkos_Param.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/tests/Test_StateVectorLKokkos.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/utils/UtilKokkos.hpp
  pennylane_lightning/core/src/utils/Util.hpp
  pennylane_lightning/lightning_kokkos/_state_vector.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.toml
  tests/test_gates.py
Labels: ci:build_wheels, urgent, ci:use-gpu-runner

#953 (LK-C-2) Add controlled named 2/4-qubit gate (e.g. NCIsingXX) support to Lightning Kokkos
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/BasicGateFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/BasicGeneratorFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/tests/Test_StateVectorKokkos_NonParam.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/tests/Test_StateVectorKokkos_Param.cpp
  pennylane_lightning/lightning_kokkos/_state_vector.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.toml
  tests/test_gates.py
Labels: ci:build_wheels, urgent, ci:use-gpu-runner

#960 Downstream LightningSimulator C++ API to the pennylane-lightning repository
  .github/CHANGELOG.md
  .github/workflows/tests_lqcpu_python.yml
  cmake/support_catalyst.cmake
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_qubit/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/LightningObsManager.hpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/LightningSimulator.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/LightningSimulator.hpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/StateVectorLQubitDynamic.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/StateVectorLQubitDynamic.hpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/tests/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/tests/Test_LightningDriver.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/tests/Test_LightningGradient.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/tests/Test_LightningMeasures.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/tests/Test_LightningSimulator.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/tests/Test_SVDynamicCPU_Allocation.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/tests/Test_SVDynamicCPU_Core.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/tests/runner_lightning_qubit_catalyst.cpp
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  setup.py
  tests/test_device.py
Labels: ci:build_wheels, urgent

#994 Remove Tensor and Hamiltonian in python frontend for lightning
  .github/CHANGELOG.md
  pennylane_lightning/core/_measurements_base.py
  pennylane_lightning/core/_serialize.py
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/lightning_base.py
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  pennylane_lightning/lightning_tensor/lightning_tensor.py
  tests/conftest.py
  tests/lightning_qubit/test_adjoint_jacobian_class.py
  tests/lightning_qubit/test_jacobian_method.py
  tests/new_api/test_device.py
  tests/test_adjoint_jacobian.py
  tests/test_execute.py
  tests/test_measurements.py
  tests/test_serialize.py
  tests/test_vjp.py
Labels: ci:use-gpu-runner

#954 (LK-C-3) Add controlled MultiRZ support to Lightning Kokkos
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/BasicGateFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/tests/Test_StateVectorKokkos_Param.cpp
  pennylane_lightning/lightning_kokkos/_state_vector.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.toml
  tests/test_gates.py
Labels: ci:build_wheels, urgent, ci:use-gpu-runner

#996 Fix the issue with adjoint-jacobian of adjoint ops
  .github/CHANGELOG.md
  pennylane_lightning/core/_serialize.py
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/tests/Test_LightningGradient.cpp
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  tests/test_adjoint_jacobian.py
Labels: ci:build_wheels, urgent, ci:use-gpu-runner

#955 (LK-C-4) Add controlled QubitUnitary support to Lightning Kokkos
  pennylane_lightning/core/src/simulators/lightning_kokkos/StateVectorKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/bindings/LKokkosBindings.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/BasicGateFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/BasicGeneratorFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/MatrixGateFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/tests/Test_StateVectorKokkos_NonParam.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/tests/Test_StateVectorKokkos_Param.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/measurements/MeasurementsKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/tests/Test_StateVectorLKokkos.cpp
  pennylane_lightning/lightning_kokkos/_state_vector.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.toml
  tests/lightning_qubit/test_measurements_class.py
  tests/test_gates.py
Labels: ci:build_wheels, urgent, ci:use-gpu-runner

#999 Remove SVDynamic
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/LightningObsManager.hpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/LightningSimulator.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/LightningSimulator.hpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/StateVectorLQubitDynamic.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/StateVectorLQubitDynamic.hpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/tests/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/tests/Test_LightningDriver.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/tests/Test_LightningSimulator.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/tests/Test_SVDynamicCPU_Allocation.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/tests/Test_SVDynamicCPU_Core.cpp
Labels: ci:build_wheels

#979 Standard installation instruction visibility
  .github/CHANGELOG.md
  README.rst
  pennylane_lightning/core/_version.py
Labels: documentation

#956 (LK-C-5) Add controlled generator (1-qubit) support for Lightning Kokkos
  pennylane_lightning/core/src/simulators/lightning_kokkos/StateVectorKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/BasicGeneratorFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/tests/Test_StateVectorKokkos_Generator.cpp
Labels: ci:build_wheels, urgent, ci:use-gpu-runner

#988 Update Lightning device TOML files to the new schema
  .github/CHANGELOG.md
  doc/requirements.txt
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_gpu/lightning_gpu.toml
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.toml
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  pennylane_lightning/lightning_qubit/lightning_qubit.toml
  tests/test_gates.py
Labels: ci:build_wheels, urgent, ci:use-gpu-runner

#958 (LK-C-6) Add controlled generator (multi-qubit) support for Lightning Kokkos
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/BasicGeneratorFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/tests/Test_StateVectorKokkos_Generator.cpp
Labels: ci:build_wheels, urgent, ci:use-gpu-runner

#965 (LK-C-7) Add controlled adjoint support for Lightning Kokkos
  pennylane_lightning/core/src/algorithms/tests/Test_AdjointJacobian.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/algorithms/AdjointJacobianKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/algorithms/tests/Test_AdjointJacobianKokkos.cpp
  tests/lightning_qubit/test_adjoint_jacobian_class.py
Labels: ci:build_wheels, urgent, ci:use-gpu-runner

#993 LGPU-MPI installation instruction update and missing lib message update
  .github/CHANGELOG.md
  README.rst
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_gpu/MPIWorker.hpp
Labels: ci:use-multi-gpu-runner

#1004 Fix Lightning GPU Rot adjoint bug and enable Rot in toml
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_gpu/StateVectorCudaMPI.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/StateVectorCudaManaged.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/gates/tests/Test_StateVectorCudaManaged_Param.cpp
  pennylane_lightning/lightning_gpu/lightning_gpu.toml
Labels: ci:use-multi-gpu-runner, ci:build_wheels, urgent, ci:use-gpu-runner

#1000 Fix the applyMatrix cudaFree segfault on LK+CUDA
  .github/CHANGELOG.md
  .github/workflows/build_and_cache_Kokkos_linux.yml
  .github/workflows/set_wheel_build_matrix.yml
  .github/workflows/tests_lkcpu_python.yml
  .github/workflows/tests_lkcuda_cpp.yml
  .github/workflows/tests_lkcuda_python.yml
  .github/workflows/tests_windows_cpp.yml
  README.rst
  cmake/support_kokkos.cmake
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/base/tests/Test_StateVectorBase.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/StateVectorKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/algorithms/tests/Test_AdjointJacobianKokkos.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/tests/Test_LightningKokkosSimulator.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/tests/Test_StateVectorKokkos_Param.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/measurements/tests/Test_StateVectorKokkos_Measure.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/observables/tests/Test_ObservablesKokkos.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/tests/Test_StateVectorLKokkos.cpp
  pennylane_lightning/core/src/utils/TestHelpers.hpp
Labels: ci:use-gpu-runner

#1009 update LQ generator vector insert order
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_qubit/gates/cpu_kernels/GateImplementationsLM.hpp
Labels: ci:build_wheels, urgent

#1005 LGPU simulator support controlled ops
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_gpu/catalyst/LightningGPUSimulator.cpp
  pennylane_lightning/core/src/simulators/lightning_gpu/catalyst/tests/Test_LightningGPUSimulator.cpp
Labels: ci:build_wheels, urgent, ci:use-gpu-runner

#1007 Fix the missing ninja in AARCH64 Linux wheel recipe
  .github/CHANGELOG.md
  .github/workflows/build_and_cache_Kokkos_linux.yml
  .github/workflows/set_wheel_build_matrix.yml
  .github/workflows/tests_lkcpu_python.yml
  .github/workflows/tests_lkcuda_cpp.yml
  .github/workflows/tests_lkcuda_python.yml
  .github/workflows/tests_windows_cpp.yml
  .github/workflows/wheel_linux_aarch64.yml
  README.rst
  cmake/support_kokkos.cmake
  pennylane_lightning/core/_version.py
Labels: ci:build_wheels, urgent
