Repository PennyLaneAI/pennylane-lightning, pull requests merged in 2024-09, with the labels that each got.

#810 Create a base LKokkos new device API backend.
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_kokkos/_adjoint_jacobian.py
  pennylane_lightning/lightning_kokkos/_measurements.py
  pennylane_lightning/lightning_kokkos/_state_vector.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  tests/conftest.py
  tests/lightning_qubit/test_adjoint_jacobian_class.py
  tests/lightning_qubit/test_jacobian_method.py
  tests/lightning_qubit/test_measurements_class.py
  tests/lightning_qubit/test_measurements_samples_MCMC.py
  tests/lightning_qubit/test_simulate_method.py
  tests/lightning_qubit/test_state_vector_class.py
  tests/new_api/test_device.py
  tests/test_adjoint_jacobian.py
  tests/test_device.py
  tests/test_native_mcm.py
Labels: ci:build_wheels

#887 Update/actions
  .github/CHANGELOG.md
  .github/workflows/docker_linux_x86_64.yml
  .github/workflows/post_release_version_bump.yml
  .github/workflows/pre_release_version_bump.yml
  .github/workflows/tests_lgpu_cpp.yml
  .github/workflows/tests_lgpu_python.yml
  .github/workflows/tests_lgpumpi_cpp.yml
  .github/workflows/tests_lgpumpi_python.yml
  .github/workflows/tests_linux_cpp.yml
  .github/workflows/tests_lkcpu_python.yml
  .github/workflows/tests_lkcuda_cpp.yml
  .github/workflows/tests_lkcuda_python.yml
  .github/workflows/tests_lmps_tncuda_cpp.yml
  .github/workflows/tests_lmps_tncuda_python.yml
  .github/workflows/tests_lqcpu_python.yml
  .github/workflows/tests_windows_cpp.yml
  .github/workflows/wheel_linux_aarch64.yml
  .github/workflows/wheel_linux_aarch64_cuda.yml
  .github/workflows/wheel_linux_ppc64le.yml
  .github/workflows/wheel_linux_x86_64.yml
  .github/workflows/wheel_linux_x86_64_cuda.yml
  .github/workflows/wheel_macos_arm64.yml
  .github/workflows/wheel_macos_x86_64.yml
  .github/workflows/wheel_noarch.yml
  .github/workflows/wheel_win_x86_64.yml
  pennylane_lightning/core/_version.py
Labels: github_actions

#873 Chunk Hamiltonian, PauliSentence, LinearCombination [sc-65680]
  .github/CHANGELOG.md
  .github/workflows/tests_lgpu_cpp.yml
  pennylane_lightning/core/_serialize.py
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/lightning_base.py
  pennylane_lightning/core/src/simulators/lightning_gpu/algorithms/AdjointJacobianGPU.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/observables/ObservablesGPU.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/observables/ObservablesKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_qubit/StateVectorLQubitManaged.hpp
  pennylane_lightning/core/src/simulators/lightning_qubit/observables/ObservablesLQubit.hpp
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_kokkos/_adjoint_jacobian.py
  pennylane_lightning/lightning_qubit/_adjoint_jacobian.py
  pennylane_lightning/lightning_qubit/_state_vector.py
  tests/test_adjoint_jacobian.py
  tests/test_serialize_chunk_obs.py
Labels: ci:use-multi-gpu-runner, ci:build_wheels

#890 Fix the artifact name in LGPU and remove old installation commands in stable installation of LQ & LK
  .github/workflows/tests_lgpu_python.yml
  .github/workflows/tests_lkcpu_python.yml
  .github/workflows/tests_lqcpu_python.yml
  pennylane_lightning/core/_version.py
Labels: ci:build_wheels

#891 Update Py3.9 to 3.10 minimum
  .github/CHANGELOG.md
  .github/workflows/post_release_version_bump.yml
  .github/workflows/pre_release_version_bump.yml
  .github/workflows/set_wheel_build_matrix.yml
  .github/workflows/tests_lgpu_cpp.yml
  .github/workflows/tests_lgpu_python.yml
  .github/workflows/tests_lgpumpi_cpp.yml
  .github/workflows/tests_linux_cpp.yml
  .github/workflows/tests_lkcpu_python.yml
  .github/workflows/tests_lkcuda_cpp.yml
  .github/workflows/tests_lkcuda_python.yml
  .github/workflows/tests_lmps_tncuda_cpp.yml
  .github/workflows/tests_lmps_tncuda_python.yml
  .github/workflows/tests_lqcpu_python.yml
  .github/workflows/tests_windows_cpp.yml
  .github/workflows/tests_without_binary.yml
  .github/workflows/update_dev_version.yml
  .github/workflows/wheel_linux_aarch64.yml
  .github/workflows/wheel_linux_aarch64_cuda.yml
  .github/workflows/wheel_linux_ppc64le.yml
  .github/workflows/wheel_linux_x86_64.yml
  .github/workflows/wheel_linux_x86_64_cuda.yml
  .github/workflows/wheel_macos_arm64.yml
  .github/workflows/wheel_macos_x86_64.yml
  .github/workflows/wheel_noarch.yml
  .github/workflows/wheel_win_x86_64.yml
  .readthedocs.yml
  README.rst
  pyproject.toml
Labels: ci:build_wheels, urgent

#893 Migrate wheels artifacts to v4
  .github/CHANGELOG.md
  .github/workflows/tests_lgpu_cpp.yml
  .github/workflows/tests_lgpumpi_cpp.yml
  .github/workflows/tests_lgpumpi_python.yml
  .github/workflows/tests_linux_cpp.yml
  .github/workflows/wheel_linux_aarch64.yml
  .github/workflows/wheel_linux_aarch64_cuda.yml
  .github/workflows/wheel_linux_ppc64le.yml
  .github/workflows/wheel_linux_x86_64.yml
  .github/workflows/wheel_linux_x86_64_cuda.yml
  .github/workflows/wheel_macos_arm64.yml
  .github/workflows/wheel_macos_x86_64.yml
  .github/workflows/wheel_win_x86_64.yml
  pennylane_lightning/core/_version.py
Labels: ci:build_wheels, urgent

#901 Update ecosystem build tooling
  .github/CHANGELOG.md
  .github/workflows/wheel_linux_aarch64.yml
  .github/workflows/wheel_linux_aarch64_cuda.yml
  .github/workflows/wheel_linux_x86_64.yml
  .github/workflows/wheel_linux_x86_64_cuda.yml
  .github/workflows/wheel_macos_arm64.yml
  .github/workflows/wheel_macos_x86_64.yml
  .github/workflows/wheel_win_x86_64.yml
  CMakeLists.txt
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  pennylane_lightning/lightning_tensor/lightning_tensor.py
  pyproject.toml
  scripts/configure_pyproject_toml.py
  setup.py
Labels: ci:build_wheels

#855 Add native PauliRot implementation in LightningKokkos [sc-71642]
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_kokkos/StateVectorKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/bindings/LKokkosBindings.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/BasicGateFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/tests/Test_StateVectorKokkos_Param.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/gates/cpu_kernels/GateImplementationsLM.hpp
  pennylane_lightning/lightning_kokkos/_state_vector.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  tests/test_gates.py
Labels: ci:build_wheels

#897 Import QubitDevice from devices module
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/lightning_base.py
Labels: urgent

#852 Add shot measurement support to `lightning.tensor`
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/bindings/Bindings.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/measurements/MeasurementsTNCuda.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/measurements/tests/Test_MPSTNCuda_Measure.cpp
  pennylane_lightning/core/src/utils/TestHelpers.hpp
  pennylane_lightning/core/src/utils/cuda_utils/tests/CMakeLists.txt
  pennylane_lightning/lightning_tensor/_measurements.py
  pennylane_lightning/lightning_tensor/_tensornet.py
  pennylane_lightning/lightning_tensor/lightning_tensor.py
  tests/conftest.py
  tests/lightning_qubit/test_measurements_class.py
  tests/lightning_tensor/test_gates_and_expval.py
  tests/lightning_tensor/test_lightning_tensor.py
  tests/lightning_tensor/test_measurements_class.py
  tests/test_apply.py
  tests/test_measurements.py
Labels: urgent

#904 Skip binaries in the docs build script
  .github/CHANGELOG.md
  .readthedocs.yml
  Makefile
  doc/conf.py
  doc/requirements.txt
  pennylane_lightning/core/_version.py
Labels: urgent

#882 Optimize LM controlled kernels [sc-73461]
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_qubit/gates/GateIndices.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/gates/GateIndices.hpp
  pennylane_lightning/core/src/simulators/lightning_qubit/gates/cpu_kernels/GateImplementationsLM.hpp
Labels: ci:build_wheels, urgent

#906 Fix qml.probs for lightning.tensor
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/TNCudaBase.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/measurements/MeasurementsTNCuda.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/measurements/tests/Test_MPSTNCuda_Measure.cpp
  pennylane_lightning/core/src/utils/cuda_utils/LinearAlg.hpp
  tests/lightning_tensor/test_measurements_class.py
Labels: bug-fix, urgent

#903 Build wheels in the Release mode
  .github/CHANGELOG.md
  .github/workflows/wheel_linux_aarch64.yml
  .github/workflows/wheel_linux_aarch64_cuda.yml
  .github/workflows/wheel_linux_x86_64.yml
  .github/workflows/wheel_linux_x86_64_cuda.yml
  .github/workflows/wheel_macos_arm64.yml
  .github/workflows/wheel_macos_x86_64.yml
  .github/workflows/wheel_win_x86_64.yml
  pennylane_lightning/core/_version.py
Labels: urgent

#892 Add the `state_vector`, `measurement` class and `simulate` method for the LightningGPU with the new device API
  pennylane_lightning/core/_measurements_base.py
  pennylane_lightning/core/_state_vector_base.py
  pennylane_lightning/core/src/simulators/lightning_gpu/StateVectorCudaManaged.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/bindings/LGPUBindings.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/bindings/LGPUBindingsMPI.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/measurements/MeasurementsGPU.hpp
  pennylane_lightning/lightning_gpu/_measurements.py
  pennylane_lightning/lightning_gpu/_mpi_handler.py
  pennylane_lightning/lightning_gpu/_state_vector.py
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_kokkos/_measurements.py
  pennylane_lightning/lightning_qubit/_measurements.py
  tests/conftest.py
  tests/lightning_qubit/test_measurements_class.py
  tests/lightning_qubit/test_simulate_method.py
  tests/lightning_qubit/test_state_vector_class.py
Labels: urgent

#907 Add the support class for the Adjoint Jacobian to the new device
  pennylane_lightning/core/_state_vector_base.py
  pennylane_lightning/core/lightning_newAPI_base.py
  pennylane_lightning/lightning_gpu/_adjoint_jacobian.py
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_kokkos/_state_vector.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  tests/conftest.py
  tests/lightning_qubit/test_adjoint_jacobian_class.py
  tests/lightning_qubit/test_jacobian_method.py
Labels: urgent

#912 Test changes to account for 0.39 deprecations
  .github/CHANGELOG.md
  mpitests/test_adjoint_jacobian.py
  pennylane_lightning/core/_version.py
  tests/test_adjoint_jacobian.py
Labels: ci:use-multi-gpu-runner, urgent

#859 Add MPO support to `lightning.tensor`
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/MPOTNCuda.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/MPOTNCuda.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/MPSTNCuda.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/bindings/LTensorTNCudaBindings.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/gates/tests/Test_MPSTNCuda_NonParam.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/gates/tests/Test_MPSTNCuda_Param.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/tests/Tests_MPSTNCuda.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/utils/tncuda_utils/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/utils/tncuda_utils/tests/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/utils/tncuda_utils/tests/Test_TNCuda_utils.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/utils/tncuda_utils/tests/runner_lightning_tensor_tncuda_utils.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/utils/tncuda_utils/tncuda_helpers.hpp
  pennylane_lightning/lightning_tensor/_tensornet.py
  pennylane_lightning/lightning_tensor/lightning_tensor.py
  tests/lightning_qubit/test_measurements_class.py
  tests/lightning_tensor/test_gates_and_expval.py
  tests/lightning_tensor/test_tensornet_class.py
  tests/test_apply.py
  tests/test_execute.py
  tests/test_gates.py
  tests/test_measurements.py
  tests/test_templates.py
Labels: ci:build_wheels, urgent

#908 Add (check) full support for sampling in full parity with Lightning.
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  tests/lightning_qubit/test_measurements_samples_MCMC.py
  tests/new_api/test_device.py
  tests/new_api/test_expval.py
  tests/new_api/test_var.py
Labels: urgent, ci:use-gpu-runner

#911 Merge lightning.gpu and lightning.tensor test CIs and add control by a label
  .github/CHANGELOG.md
  .github/workflows/tests_gpu_cpp.yml
  .github/workflows/tests_gpu_python.yml
  .github/workflows/tests_lgpu_python.yml
  .github/workflows/tests_lmps_tncuda_cpp.yml
  pennylane_lightning/core/_version.py
Labels: urgent, ci:use-gpu-runner

#909 Update ``lightning.tensor`` docs
  .github/CHANGELOG.md
  CMakeLists.txt
  README.rst
  doc/lightning_tensor/device.rst
  pennylane_lightning/core/_version.py
Labels: do not merge, urgent

#918 Update plugin test matrix GPU workflow names
  .github/workflows/compat-check-latest-latest.yml
  .github/workflows/compat-check-latest-stable.yml
  .github/workflows/compat-check-release-release.yml
  .github/workflows/compat-check-stable-latest.yml
  .github/workflows/compat-check-stable-stable.yml
  pennylane_lightning/core/_version.py
Labels: urgent

#919 Enable `enable_new_opmath` for `lightning.tensor`
  .github/CHANGELOG.md
  doc/lightning_tensor/device.rst
  pennylane_lightning/core/_serialize.py
  pennylane_lightning/core/_version.py
  tests/test_execute.py
Labels: ci:use-gpu-runner

#914 Add support for multi-GPU state-vector
  Makefile
  mpitests/conftest.py
  mpitests/test_adjoint_jacobian.py
  mpitests/test_apply.py
  mpitests/test_device.py
  mpitests/test_expval.py
  mpitests/test_measurements_sparse.py
  mpitests/test_probs.py
  pennylane_lightning/core/src/simulators/lightning_gpu/StateVectorCudaMPI.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/bindings/LGPUBindings.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/bindings/LGPUBindingsMPI.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/tests/mpi/Test_StateVectorCudaMPI.cpp
  pennylane_lightning/core/src/simulators/lightning_gpu/utils/cuStateVec_helpers.hpp
  pennylane_lightning/lightning_gpu/_measurements.py
  pennylane_lightning/lightning_gpu/_mpi_handler.py
  pennylane_lightning/lightning_gpu/_state_vector.py
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_kokkos/_state_vector.py
  pennylane_lightning/lightning_qubit/_state_vector.py
Labels: ci:use-multi-gpu-runner, urgent, ci:use-gpu-runner

#920 Patch tests after deprecation
  .github/workflows/tests_lqcpu_python.yml
  pennylane_lightning/core/_version.py
Labels: urgent

#921 Add support for multi-GPU measurement and Adjoint Jacobian processes
  MANIFEST.in
  mpitests/test_adjoint_jacobian.py
  mpitests/test_apply.py
  mpitests/test_expval.py
  mpitests/test_measurements_sparse.py
  mpitests/test_probs.py
  pennylane_lightning/core/_measurements_base.py
  pennylane_lightning/lightning_gpu/_adjoint_jacobian.py
  pennylane_lightning/lightning_gpu/_measurements.py
  pennylane_lightning/lightning_gpu/_state_vector.py
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  tests/test_adjoint_jacobian.py
Labels: ci:use-multi-gpu-runner, urgent, ci:use-gpu-runner

#923 Update unit/integration tests for the new device
  .github/workflows/tests_lgpu_python.yml
  pennylane_lightning/lightning_gpu/_adjoint_jacobian.py
  pennylane_lightning/lightning_gpu/_measurements.py
  pennylane_lightning/lightning_gpu/_mpi_handler.py
  pennylane_lightning/lightning_gpu/_state_vector.py
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_kokkos/_adjoint_jacobian.py
  pennylane_lightning/lightning_kokkos/_measurements.py
  pennylane_lightning/lightning_kokkos/_state_vector.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_qubit/_adjoint_jacobian.py
  pennylane_lightning/lightning_qubit/_measurements.py
  pennylane_lightning/lightning_qubit/_state_vector.py
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  tests/test_apply.py
  tests/test_comparison.py
  tests/test_device.py
  tests/test_execute.py
  tests/test_expval.py
  tests/test_gates.py
  tests/test_measurements.py
  tests/test_measurements_sparse.py
  tests/test_native_mcm.py
  tests/test_templates.py
  tests/test_var.py
  tests/test_vjp.py
Labels: ci:use-multi-gpu-runner, ci:build_wheels, urgent, ci:use-gpu-runner

#926 Remove magic numbers in Lightning stopping_conditions
  .github/CHANGELOG.md
  README.rst
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/lightning_base.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  pennylane_lightning/lightning_tensor/lightning_tensor.py
  tests/test_templates.py
Labels: ci:use-multi-gpu-runner, ci:build_wheels, urgent
