Repository PennyLaneAI/pennylane-lightning, pull requests merged in 2024-03, with the labels that each got.

#623 Introduce isort.
  .github/CHANGELOG.md
  Makefile
  mpitests/conftest.py
  mpitests/test_adjoint_jacobian.py
  mpitests/test_apply.py
  mpitests/test_device.py
  mpitests/test_expval.py
  mpitests/test_measurements_sparse.py
  mpitests/test_probs.py
  pennylane_lightning/core/_serialize.py
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/lightning_base.py
  pennylane_lightning/lightning_gpu/__init__.py
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_kokkos/__init__.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_qubit/__init__.py
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  requirements-dev.txt
  tests/conftest.py
  tests/lightning_qubit/test_measurements_samples_MCMC.py
  tests/test_adjoint_jacobian.py
  tests/test_apply.py
  tests/test_arrays.py
  tests/test_binary_info.py
  tests/test_comparison.py
  tests/test_decomposition.py
  tests/test_device.py
  tests/test_execute.py
  tests/test_expval.py
  tests/test_gates.py
  tests/test_measurements.py
  tests/test_measurements_sparse.py
  tests/test_serialize.py
  tests/test_serialize_chunk_obs.py
  tests/test_serialize_no_binaries.py
  tests/test_var.py
  tests/test_vjp.py
Labels: ci:use-multi-gpu-runner

#648 Only build wheels when label build_wheels is activated.
  .github/CHANGELOG.md
  .github/workflows/wheel_linux_x86_64.yml
  .github/workflows/wheel_linux_x86_64_cuda.yml
  .github/workflows/wheel_macos_arm64.yml
  .github/workflows/wheel_macos_x86_64.yml
  .github/workflows/wheel_noarch.yml
  .github/workflows/wheel_win_x86_64.yml
  pennylane_lightning/core/_version.py
Labels: ci:build_wheels

#647 Fix isort config
  .github/CHANGELOG.md
  .github/workflows/format.yml
  Makefile
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_qubit/_measurements.py
  tests/lightning_qubit/test_adjoint_jacobian_class.py
  tests/lightning_qubit/test_measurements_class.py
  tests/test_serialize.py
Labels: ci:build_wheels

#650 Add MCM support in LQ (new device API)
  .github/CHANGELOG.md
  .github/workflows/format.yml
  .github/workflows/tests_linux.yml
  mpitests/test_adjoint_jacobian.py
  pennylane_lightning/core/_serialize.py
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_qubit/bindings/LQubitBindings.hpp
  pennylane_lightning/lightning_qubit/_measurements.py
  pennylane_lightning/lightning_qubit/_state_vector.py
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  tests/conftest.py
  tests/new_api/test_device.py
  tests/test_adjoint_jacobian.py
  tests/test_native_mcm.py
Labels: ci:build_wheels

#661 Fix state prep operation decomposition with `LightningQubit`
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  tests/new_api/test_device.py
Labels: ci:build_wheels

#662 Comment triggers.
  .github/workflows/tests_linux_x86_mpi_gpu.yml
Labels: ci:use-multi-gpu-runner

#649 Add support for `LinearCombination`
  .github/CHANGELOG.md
  .github/workflows/tests_gpu_cuda.yml
  .github/workflows/tests_linux_x86_mpi_gpu.yml
  .github/workflows/wheel_macos_x86_64.yml
  .github/workflows/wheel_noarch.yml
  .github/workflows/wheel_win_x86_64.yml
  mpitests/test_apply.py
  pennylane_lightning/core/_serialize.py
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/lightning_base.py
  pennylane_lightning/core/src/bindings/Bindings.hpp
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  requirements-dev.txt
  tests/conftest.py
  tests/lightning_qubit/test_adjoint_jacobian_class.py
  tests/lightning_qubit/test_measurements_class.py
  tests/new_api/test_device.py
  tests/test_adjoint_jacobian.py
  tests/test_execute.py
  tests/test_measurements.py
  tests/test_serialize.py
  tests/test_vjp.py
Labels: ci:use-multi-gpu-runner, ci:build_wheels

#663 Trigger CI for TestPyPI
  pennylane_lightning/core/_version.py
Labels: ci:build_wheels
