Repository PennyLaneAI/pennylane-lightning, pull requests merged in 2024-08, with the labels that each got.

#829 Add the support class for the Adjoint Jacobian to the new device
  pennylane_lightning/lightning_kokkos/_adjoint_jacobian.py
  pennylane_lightning/lightning_kokkos/_state_vector.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  tests/lightning_qubit/test_adjoint_jacobian_class.py
  tests/lightning_qubit/test_jacobian_method.py
Labels: ci:build_wheels

#837 Implement get_c_interface method for Kokkos plugin
  .github/CHANGELOG.md
  .github/workflows/tests_lkcpu_python.yml
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  tests/test_device.py
Labels: ci:build_wheels

#845 Bug fix for cutensornet v2.5.0
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/TNCudaBase.hpp
Labels: bug

#832 Update Lightning packaging to follow the PEP 517/518/621/660 standards
  .github/CHANGELOG.md
  .github/workflows/format.yml
  .github/workflows/tests_lgpu_python.yml
  .github/workflows/tests_lgpumpi_python.yml
  .github/workflows/tests_lkcpu_python.yml
  .github/workflows/tests_lkcuda_python.yml
  .github/workflows/tests_lmps_tncuda_python.yml
  .github/workflows/tests_lqcpu_python.yml
  .github/workflows/tests_windows_cpp.yml
  .github/workflows/tests_without_binary.yml
  .github/workflows/wheel_linux_aarch64.yml
  .github/workflows/wheel_linux_ppc64le.yml
  .github/workflows/wheel_linux_x86_64.yml
  .github/workflows/wheel_linux_x86_64_cuda.yml
  .github/workflows/wheel_macos_arm64.yml
  .github/workflows/wheel_macos_x86_64.yml
  .github/workflows/wheel_noarch.yml
  .github/workflows/wheel_win_x86_64.yml
  .gitignore
  .readthedocs.yml
  CMakeLists.txt
  MANIFEST.in
  Makefile
  README.rst
  docker/Dockerfile
  pennylane_lightning/core/__init__.py
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_gpu/__init__.py
  pennylane_lightning/lightning_kokkos/__init__.py
  pennylane_lightning/lightning_qubit/__init__.py
  pyproject.toml
  requirements-dev.txt
  scripts/backend_support.py
  scripts/configure_pyproject_toml.py
  scripts/gen_pyver_matrix.py
  setup.py
Labels: ci:build_wheels

#840 Update unit/integration tests for the new device
  .github/workflows/tests_lkcpu_python.yml
  .github/workflows/tests_lkcuda_python.yml
  .github/workflows/wheel_linux_aarch64.yml
  .github/workflows/wheel_linux_x86_64.yml
  .github/workflows/wheel_macos_arm64.yml
  .github/workflows/wheel_macos_x86_64.yml
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  tests/test_adjoint_jacobian.py
  tests/test_apply.py
  tests/test_comparison.py
  tests/test_device.py
  tests/test_execute.py
  tests/test_expval.py
  tests/test_gates.py
  tests/test_measurements.py
  tests/test_measurements_sparse.py
  tests/test_templates.py
  tests/test_var.py
  tests/test_vjp.py
Labels: ci:build_wheels

#850 Fix/lightning tests
  .github/CHANGELOG.md
  .github/workflows/tests_lgpu_python.yml
  .github/workflows/tests_lgpumpi_python.yml
  .github/workflows/tests_lkcpu_python.yml
  .github/workflows/tests_lkcuda_python.yml
  .github/workflows/tests_lqcpu_python.yml
  .github/workflows/tests_without_binary.yml
  pennylane_lightning/core/_version.py
Labels: ci:build_wheels

#858 Fix the long_description issues in Lightning
  .github/CHANGELOG.md
  README.rst
  pennylane_lightning/core/_version.py
Labels: ci:build_wheels

#864 Support the generalization of basis state preparation and the facade legacy device for MPI LGPU
  .github/CHANGELOG.md
  mpitests/test_adjoint_jacobian.py
  mpitests/test_apply.py
  pennylane_lightning/core/_version.py
  tests/lightning_qubit/test_state_vector_class.py
  tests/lightning_tensor/test_tensornet_class.py
  tests/new_api/test_device.py
  tests/test_apply.py
Labels: ci:use-multi-gpu-runner

#861 Add SetState and SetBasisState to kokkos
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_kokkos/StateVectorKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/LightningKokkosSimulator.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/LightningKokkosSimulator.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/tests/Test_LightningKokkosSimulator.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/tests/Test_StateVectorLKokkos.cpp
Labels: ci:build_wheels

#867 Downgrade pb
  .github/CHANGELOG.md
  CMakeLists.txt
  pennylane_lightning/core/_version.py
Labels: ci:build_wheels, urgent

#869 Correctly querying wire IDs for `SetState` and `SetBasisState` in kokkos
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/LightningKokkosSimulator.cpp
Labels: bug
