Repository PennyLaneAI/pennylane-lightning, pull requests merged in 2024-05, with the labels that each got.

#696 Introduce pytest-splits
  .github/CHANGELOG.md
  .github/workflows/build_and_cache_Kokkos_linux.yml
  .github/workflows/compat-check-latest-latest.yml
  .github/workflows/compat-check-latest-stable.yml
  .github/workflows/compat-check-release-release.yml
  .github/workflows/compat-check-stable-latest.yml
  .github/workflows/compat-check-stable-stable.yml
  .github/workflows/format.yml
  .github/workflows/python_lightning_kokkos_test_durations.json
  .github/workflows/python_lightning_qubit_test_durations.json
  .github/workflows/tests_lgpu_python.yml
  .github/workflows/tests_lgpumpi_python.yml
  .github/workflows/tests_linux_python.yml
  .github/workflows/tests_lkcpu_python.yml
  .github/workflows/tests_lkcuda_python.yml
  .github/workflows/tests_lqcpu_python.yml
  .github/workflows/tests_without_binary.yml
  .github/workflows/tidy.yml
  requirements-dev.txt
Labels: ci:build_wheels

#706 Update changelog
  .github/CHANGELOG.md
Labels: ci:build_wheels

#705 Use wire order specified on instantiation
  .github/CHANGELOG.md
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  tests/new_api/test_device.py
Labels: ci:build_wheels

#711 Port PR #705 changes
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  tests/new_api/test_device.py
Labels: ci:build_wheels, urgent

#707 Update wire order support for probabilities
  .github/CHANGELOG.md
  .github/workflows/tests_linux_cpp.yml
  .github/workflows/tests_lqcpu_python.yml
  README.rst
  pennylane_lightning/core/src/measurements/tests/Test_MeasurementsBase.cpp
  pennylane_lightning/core/src/simulators/lightning_gpu/measurements/MeasurementsGPU.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/measurements/MeasurementsKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/measurements/tests/Test_StateVectorKokkos_Measure.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/measurements/MeasurementsLQubit.hpp
  pennylane_lightning/core/src/simulators/lightning_qubit/measurements/tests/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_qubit/measurements/tests/Test_MeasurementsLQubit.cpp
  pennylane_lightning/core/src/utils/NDPermuter.hpp
  pennylane_lightning/core/src/utils/tests/CMakeLists.txt
  pennylane_lightning/core/src/utils/tests/Test_NDPermuter.cpp
Labels: ci:build_wheels

#715 Syncing master with V0.36.0 branch
  .github/CHANGELOG.md
  .github/workflows/build_and_cache_Kokkos_linux.yml
  .github/workflows/compat-check-latest-latest.yml
  .github/workflows/compat-check-latest-stable.yml
  .github/workflows/compat-check-release-release.yml
  .github/workflows/compat-check-stable-latest.yml
  .github/workflows/compat-check-stable-stable.yml
  .github/workflows/dev_version_script.py
  .github/workflows/format.yml
  .github/workflows/python_lightning_kokkos_test_durations.json
  .github/workflows/python_lightning_qubit_test_durations.json
  .github/workflows/tests_lgpu_python.yml
  .github/workflows/tests_lgpumpi_python.yml
  .github/workflows/tests_linux_cpp.yml
  .github/workflows/tests_lkcpu_python.yml
  .github/workflows/tests_lkcuda_python.yml
  .github/workflows/tests_lqcpu_python.yml
  .github/workflows/tests_without_binary.yml
  .github/workflows/tidy.yml
  .github/workflows/wheel_linux_aarch64.yml
  .github/workflows/wheel_linux_x86_64.yml
  .github/workflows/wheel_macos_arm64.yml
  .github/workflows/wheel_macos_x86_64.yml
  .github/workflows/wheel_win_x86_64.yml
  .gitignore
  README.rst
  mpitests/test_adjoint_jacobian.py
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/lightning_base.py
  pennylane_lightning/core/src/measurements/tests/Test_MeasurementsBase.cpp
  pennylane_lightning/core/src/simulators/lightning_gpu/measurements/MeasurementsGPU.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/measurements/MeasurementsKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/measurements/tests/Test_StateVectorKokkos_Measure.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/measurements/MeasurementsLQubit.hpp
  pennylane_lightning/core/src/simulators/lightning_qubit/measurements/tests/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_qubit/measurements/tests/Test_MeasurementsLQubit.cpp
  pennylane_lightning/core/src/utils/NDPermuter.hpp
  pennylane_lightning/core/src/utils/tests/CMakeLists.txt
  pennylane_lightning/core/src/utils/tests/Test_NDPermuter.cpp
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_qubit/_adjoint_jacobian.py
  requirements-dev.txt
  tests/conftest.py
  tests/lightning_qubit/test_adjoint_jacobian_class.py
  tests/new_api/test_device.py
  tests/new_api/test_no_binaries.py
  tests/test_adjoint_jacobian.py
  tests/test_apply.py
  tests/test_arrays.py
  tests/test_comparison.py
  tests/test_device.py
  tests/test_execute.py
  tests/test_expval.py
  tests/test_gates.py
  tests/test_serialize_no_binaries.py
  tests/test_var.py
  tests/test_vjp.py
Labels: ci:use-multi-gpu-runner, ci:build_wheels

#719 Add `default.tensor` to `setup.py`
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_tensor/backends/quimb/_mps.py
  pennylane_lightning/lightning_tensor/lightning_tensor.py
  setup.py
  tests/lightning_tensor/test_lightning_tensor.py
Labels: ci:build_wheels

#724 Update LQ's MCM treatment following dynamic_one_shot update.
  .github/CHANGELOG.md
  .github/workflows/tests_lgpu_python.yml
  .github/workflows/tests_lgpumpi_python.yml
  .github/workflows/tests_lkcpu_python.yml
  .github/workflows/tests_lkcuda_python.yml
  .github/workflows/tests_lqcpu_python.yml
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_qubit/lightning_qubit.py
Labels: urgent

#726 Pin autoray < 0.6.10
  pennylane_lightning/core/_version.py
  requirements-dev.txt
  requirements-tests.txt
  requirements.txt
Labels: ci:build_wheels

#704 Add `MPSTNCuda` class
  .github/CHANGELOG.md
  .github/workflows/tests_lmps_tncuda_cpp.yml
  CMakeLists.txt
  cmake/support_pltensortncuda.cmake
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/CMakeLists.txt
  pennylane_lightning/core/src/simulators/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/tensor/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/tensor/base/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/tensor/base/TensorBase.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tensor/tncuda/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/tensor/tncuda/TensorCuda.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tensor/tncuda/tests/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/tensor/tncuda/tests/Tests_TensorCuda.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tensor/tncuda/tests/runner_lightning_tensor_TensorCuda.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/MPSTNCuda.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/MPSTNCuda.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/TNCudaBase.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/base/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/base/TensornetBase.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/base/tests/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/base/tests/Tests_tensornetBase.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/base/tests/runner_lightning_tensor_tensornetBase.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/tests/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/tests/Tests_MPSTNCuda.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/tests/runner_lightning_tensor_MPSTNCuda.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/utils/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/utils/mps/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/utils/mps/TestHelpersMPSTNCuda.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/utils/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/utils/tncuda_utils/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/utils/tncuda_utils/tncudaError.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/utils/tncuda_utils/tncuda_helpers.hpp
  pennylane_lightning/core/src/utils/CMakeLists.txt
  pennylane_lightning/core/src/utils/cuda_utils/cuda_helpers.hpp
Labels: ci:use-multi-gpu-runner, ci:build_wheels

#640 Kokkos gate functors are templated over the coefficient interaction function
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/gates/Gates.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/StateVectorKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/algorithms/AdjointJacobianKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/algorithms/tests/Test_AdjointJacobianKokkos.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/BasicGateFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/BasicGeneratorFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/GateFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/GateFunctorsGenerator.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/GateFunctorsNonparam.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/GateFunctorsParam.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/MatrixGateFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/tests/Test_StateVectorKokkos_Generator.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/tests/Test_StateVectorKokkos_NonParam.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/tests/Test_StateVectorKokkos_Param.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/measurements/ExpValFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/measurements/MeasurementsKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/measurements/MeasuresFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/measurements/tests/Test_StateVectorKokkos_Expval.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/measurements/tests/Test_StateVectorKokkos_Measure.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/observables/ObservablesKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/tests/Test_StateVectorLKokkos.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/utils/LinearAlgebraKokkos.hpp
Labels: ci:build_wheels

#725 Bump Kokkos version to 4.3.01
  .github/CHANGELOG.md
  .github/workflows/build_and_cache_Kokkos_linux.yml
  .github/workflows/set_wheel_build_matrix.yml
  .github/workflows/tests_lkcuda_cpp.yml
  .github/workflows/tests_lkcuda_python.yml
  .github/workflows/tests_windows_cpp.yml
  cmake/support_kokkos.cmake
  docker/Dockerfile
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/gates/Gates.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/BasicGateFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/BasicGeneratorFunctors.hpp
Labels: ci:use-multi-gpu-runner, ci:build_wheels

#734 Fix PennyLane LightningKokkos and LightningQubits tests for stable/stable
  .github/CHANGELOG.md
  .github/workflows/build_and_cache_Kokkos_linux.yml
  .github/workflows/tests_lgpu_python.yml
  .github/workflows/tests_lgpumpi_cpp.yml
  .github/workflows/tests_lgpumpi_python.yml
  .github/workflows/tests_lkcpu_python.yml
  .github/workflows/tests_lkcuda_python.yml
  .github/workflows/tests_lqcpu_python.yml
  .github/workflows/tests_without_binary.yml
  pennylane_lightning/core/_version.py
Labels: ci:build_wheels

#738 Remove Autoray dependence from requirement files
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  requirements-dev.txt
  requirements-tests.txt
  requirements.txt
Labels: ci:build_wheels

#739 Fix the cuda-runtime-12-0 dependency issue on RHEL8
  .github/CHANGELOG.md
  .github/workflows/wheel_linux_x86_64_cuda.yml
  pennylane_lightning/core/_version.py
Labels: ci:build_wheels

#744 Patch Measurements.probs(wires) to Measurements.probs() when called with all wires
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_kokkos/measurements/MeasurementsKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_qubit/measurements/MeasurementsLQubit.hpp
Labels: ci:build_wheels
