Repository PennyLaneAI/pennylane-lightning, pull requests merged in 2024-12, with the labels that each got.

#1003 Generalize seeding for measurements
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/measurements/MeasurementsBase.hpp
  pennylane_lightning/core/src/measurements/tests/Test_MeasurementsBase.cpp
  pennylane_lightning/core/src/simulators/lightning_gpu/catalyst/LightningGPUSimulator.cpp
  pennylane_lightning/core/src/simulators/lightning_gpu/catalyst/LightningGPUSimulator.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/catalyst/tests/Test_LightningGPUMeasures.cpp
  pennylane_lightning/core/src/simulators/lightning_gpu/measurements/MeasurementsGPU.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/LightningKokkosSimulator.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/LightningKokkosSimulator.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/tests/Test_LightningKokkosMeasures.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/measurements/MeasurementsKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/LightningSimulator.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/LightningSimulator.hpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/tests/Test_LightningMeasures.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/measurements/MeasurementsLQubit.hpp
Labels: ci:build_wheels

#1002 Implement eval_jaxpr method for lightning.qubit
  .github/CHANGELOG.md
  .github/workflows/python_lightning_qubit_test_durations.json
  .github/workflows/tests_lqcpu_python.yml
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/lightning_base.py
  pennylane_lightning/core/lightning_interpreter.py
  pennylane_lightning/core/lightning_newAPI_base.py
  pennylane_lightning/lightning_tensor/_tensornet.py
  tests/test_eval_jaxpr.py
Labels: ci:build_wheels, ci:use-gpu-runner

#950 (LK-C-Base) Add native controlled operation support for Lightning Kokkos
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/algorithms/tests/Test_AdjointJacobian.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/StateVectorKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/algorithms/AdjointJacobianKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/algorithms/tests/Test_AdjointJacobianKokkos.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/bindings/LKokkosBindings.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/LightningKokkosSimulator.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/tests/Test_LightningKokkosSimulator.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/BasicGateFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/BasicGeneratorFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/MatrixGateFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/tests/Test_StateVectorKokkos_Generator.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/tests/Test_StateVectorKokkos_NonParam.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/tests/Test_StateVectorKokkos_Param.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/measurements/MeasurementsKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/tests/Test_StateVectorLKokkos.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/utils/UtilKokkos.hpp
  pennylane_lightning/lightning_kokkos/_state_vector.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.toml
  tests/lightning_qubit/test_adjoint_jacobian_class.py
  tests/lightning_qubit/test_measurements_class.py
  tests/test_gates.py
Labels: ci:build_wheels, urgent, ci:use-gpu-runner

#995 Add C++ decomposition with `scipy_openblas32`
  .github/CHANGELOG.md
  .github/workflows/tests_gpu_cpp.yml
  .github/workflows/tests_lgpumpi_cpp.yml
  .github/workflows/tests_linux_cpp.yml
  .github/workflows/tests_lkcpu_python.yml
  .github/workflows/tests_lkcuda_cpp.yml
  .github/workflows/tests_lqcpu_python.yml
  .github/workflows/tests_windows_cpp.yml
  .github/workflows/tidy.yml
  .github/workflows/wheel_linux_x86_64.yml
  .github/workflows/wheel_macos_arm64.yml
  .github/workflows/wheel_macos_x86_64.yml
  CMakeLists.txt
  Makefile
  README.rst
  cmake/FindSCIPY_OPENBLAS32.cmake
  cmake/process_options.cmake
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/measurements/tests/Test_MeasurementsBase.cpp
  pennylane_lightning/core/src/observables/Observables.hpp
  pennylane_lightning/core/src/observables/tests/Test_Observables.cpp
  pennylane_lightning/core/src/simulators/lightning_gpu/StateVectorCudaManaged.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/bindings/LGPUBindings.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/catalyst/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_gpu/catalyst/tests/Test_LightningGPUMeasures.cpp
  pennylane_lightning/core/src/simulators/lightning_gpu/gates/tests/Test_StateVectorCudaManaged_NonParam.cpp
  pennylane_lightning/core/src/simulators/lightning_gpu/gates/tests/Test_StateVectorCudaManaged_Param.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/tests/Test_LightningKokkosMeasures.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_qubit/catalyst/tests/Test_LightningMeasures.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/CMakeLists.txt
  pennylane_lightning/core/src/utils/BLASLibLoaderManager.hpp
  pennylane_lightning/core/src/utils/CMakeLists.txt
  pennylane_lightning/core/src/utils/SharedLibLoader.hpp
  pennylane_lightning/core/src/utils/UtilLinearAlg.hpp
  pennylane_lightning/core/src/utils/tests/CMakeLists.txt
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  scripts/configure_pyproject_toml.py
  setup.py
Labels: ci:build_wheels, urgent

#1015 reduce flaky tests
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  tests/lightning_qubit/test_measurements_class.py
  tests/test_measurements.py
Labels: ci:build_wheels, urgent, ci:use-gpu-runner

#977 Add exact tensor network C++ backend to LT
  .github/CHANGELOG.md
  CMakeLists.txt
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/ExactTNCuda.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/ExactTNCuda.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/MPSTNCuda.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/TNCuda.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/TNCudaBase.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/base/TNCudaBase.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/base/TensornetBase.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/base/tests/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/base/tests/Tests_TNCudaBase.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/base/tests/runner_lightning_tensor_TNCudaBase.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/bindings/LTensorTNCudaBindings.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/gates/tests/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/gates/tests/Test_MPSTNCuda_NonParam.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/gates/tests/Test_MPSTNCuda_Param.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/gates/tests/Test_TNCuda_MPO.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/gates/tests/Test_TNCuda_NonParam.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/gates/tests/Test_TNCuda_Param.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/measurements/tests/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/measurements/tests/Test_TNCuda_Expval.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/measurements/tests/Test_TNCuda_Measure.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/measurements/tests/Test_TNCuda_Var.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/observables/ObservablesTNCuda.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/tests/Tests_MPSTNCuda.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/utils/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/utils/tn/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/utils/tn/TestHelpersTNCuda.hpp
Labels: urgent, ci:use-gpu-runner

#1018 Fix hipcc + lightning_kokkos issue
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/BasicGateFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/BasicGeneratorFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/MatrixGateFunctors.hpp
Labels: ci:build_wheels, ci:use-gpu-runner

#1022 Update LT python UI
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_tensor/_measurements.py
  pennylane_lightning/lightning_tensor/_tensornet.py
  pennylane_lightning/lightning_tensor/lightning_tensor.py
  tests/lightning_tensor/test_lightning_tensor.py
Labels: ci:use-gpu-runner

#1023 Upgrade LK/LGPU CI tests to use cuda 12.4
  .github/CHANGELOG.md
  .github/workflows/tests_gpu_cpp.yml
  .github/workflows/tests_gpu_python.yml
  .github/workflows/tests_lkcuda_cpp.yml
  .github/workflows/tests_lkcuda_python.yml
  pennylane_lightning/core/_version.py
Labels: ci:build_wheels, ci:use-gpu-runner

#1027 Adding unit test for measurement with shots for LT with `tn` method
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  tests/conftest.py
  tests/lightning_qubit/test_measurements_class.py
Labels: ci:use-gpu-runner

#1028 Add the `CaptureMPSState()` API to LT
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/MPSTNCuda.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/TNCuda.hpp
Labels: ci:use-gpu-runner

#983 Optimize `lightning.tensor` by adding direct MPS sites data set
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/TNCuda.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/bindings/LTensorTNCudaBindings.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/tests/Tests_MPSTNCuda.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/utils/tncuda_utils/tests/Test_TNCuda_utils.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/utils/tncuda_utils/tncuda_helpers.hpp
  pennylane_lightning/core/src/utils/Util.hpp
  pennylane_lightning/lightning_tensor/_tensornet.py
  pennylane_lightning/lightning_tensor/lightning_tensor.py
  tests/lightning_tensor/test_lightning_tensor.py
  tests/lightning_tensor/test_tensornet_class.py
Labels: ci:use-gpu-runner
