Repository PennyLaneAI/pennylane-lightning, pull requests merged in 2024-06, with the labels that each got.

#743 Add support for C(BlockEncode)
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_gpu/lightning_gpu.toml
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.toml
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  pennylane_lightning/lightning_qubit/lightning_qubit.toml
  tests/test_apply.py
Labels: ci:use-multi-gpu-runner, ci:build_wheels

#736 Update `LightningQubit` to adhere to MCM qnode arguments
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_qubit/_state_vector.py
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  tests/new_api/test_device.py
  tests/test_native_mcm.py
Labels: ci:build_wheels

#752 Change `Conditional.then_op` usage to `Conditional.base`
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_qubit/_state_vector.py
Labels: ci:build_wheels

#748 Add `pybind11` and `Python` layers to `lightning.tensor`
  .github/CHANGELOG.md
  .github/workflows/tests_lmps_tncuda_python.yml
  .github/workflows/tests_without_binary.yml
  CMakeLists.txt
  pennylane_lightning/core/_serialize.py
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/bindings/Bindings.cpp
  pennylane_lightning/core/src/bindings/Bindings.hpp
  pennylane_lightning/core/src/bindings/BindingsBase.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/MPSTNCuda.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/bindings/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/bindings/LTensorTNCudaBindings.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/gates/TNCudaGateCache.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/measurements/tests/Test_MPSTNCuda_Expval.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/observables/ObservablesTNCuda.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/utils/tncuda_utils/tncudaError.hpp
  pennylane_lightning/lightning_tensor/_measurements.py
  pennylane_lightning/lightning_tensor/_tensornet.py
  pennylane_lightning/lightning_tensor/lightning_tensor.py
  requirements-dev.txt
  setup.py
  tests/conftest.py
  tests/lightning_qubit/test_adjoint_jacobian_class.py
  tests/lightning_qubit/test_measurements_class.py
  tests/lightning_qubit/test_state_vector_class.py
  tests/lightning_tensor/test_gates_and_expval.py
  tests/lightning_tensor/test_lightning_tensor.py
  tests/lightning_tensor/test_measurements_class.py
  tests/lightning_tensor/test_tensornet_class.py
  tests/new_api/test_device.py
  tests/new_api/test_expval.py
  tests/new_api/test_var.py
  tests/test_adjoint_jacobian.py
  tests/test_apply.py
  tests/test_arrays.py
  tests/test_comparison.py
  tests/test_device.py
  tests/test_execute.py
  tests/test_expval.py
  tests/test_gates.py
  tests/test_measurements.py
  tests/test_measurements_sparse.py
  tests/test_serialize.py
  tests/test_templates.py
  tests/test_var.py
  tests/test_vjp.py
Labels: ci:use-multi-gpu-runner

#760 Add interface to `lightning.qubit` MCM preprocessing
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  tests/new_api/test_device.py
Labels: ci:build_wheels

#756 `lightning.tensor` mps docs
  .github/CHANGELOG.md
  .readthedocs.yml
  README.rst
  doc/code/__init__.rst
  doc/dev/installation.rst
  doc/index.rst
  doc/lightning_tensor/device.rst
  doc/lightning_tensor/installation.rst
  doc/lightning_tensor/package.rst
  doc/requirements.txt
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_tensor/lightning_tensor.py
Labels: ci:use-multi-gpu-runner, ci:build_wheels

#758 Fix the LK+Windows and Catalyst+Lightning latest/latest failures
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_gpu/algorithms/AdjointJacobianGPU.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/algorithms/AdjointJacobianGPUMPI.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/StateVectorKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/algorithms/AdjointJacobianKokkos.hpp
  pennylane_lightning/core/src/simulators/lightning_qubit/algorithms/AdjointJacobianLQubit.hpp
  pennylane_lightning/lightning_kokkos/lightning_kokkos.toml
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  pennylane_lightning/lightning_qubit/lightning_qubit.toml
  tests/test_device.py
Labels: ci:build_wheels

#769 Update determine runner workflow to use large runners if the branch name matches a certain format
  .github/CHANGELOG.md
  .github/workflows/determine-workflow-runner.yml
  pennylane_lightning/core/_version.py
Labels: urgent

#776 Add support for Scipy v1.14
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/utils/UtilLinearAlg.hpp
Labels: ci:build_wheels

#775 Remove Scipy config file in LQ
  .github/CHANGELOG.md
  .gitignore
  CMakeLists.txt
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/utils/UtilLinearAlg.hpp
  pennylane_lightning/core/src/utils/config.h
  pennylane_lightning/core/src/utils/config.h.in
Labels: ci:build_wheels

#772 Added pickle support for lightning.gpu device's `DevPool` attribute
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_gpu/bindings/LGPUBindings.hpp
  pennylane_lightning/core/src/utils/cuda_utils/DevicePool.hpp
  pennylane_lightning/core/src/utils/cuda_utils/TSQueue.hpp
  tests/test_device.py
Labels: ci:build_wheels
