Repository PennyLaneAI/pennylane-lightning, pull requests merged in 2024-07, with the labels that each got.

#770 Add Catalyst specific Lightning Kokkos class
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_kokkos/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/LightningKokkosObsManager.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/LightningKokkosSimulator.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/LightningKokkosSimulator.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/tests/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/tests/Test_LightningKokkosGradient.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/tests/Test_LightningKokkosMeasures.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/tests/Test_LightningKokkosSimulator.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/catalyst/tests/runner_lightning_kokkos_catalyst.cpp
Labels: ci:build_wheels

#801 Refactor CUDA Utils Python binding
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/bindings/BindingsCudaUtils.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/bindings/LGPUBindings.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/bindings/LTensorTNCudaBindings.hpp
Labels: ci:use-multi-gpu-runner, ci:build_wheels

#806 Add LTensor Hermitian wire length check
  .github/CHANGELOG.md
  pennylane_lightning/core/_serialize.py
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/observables/ObservablesTNCuda.hpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/observables/tests/Test_Observables_TNCuda.cpp
  pennylane_lightning/lightning_tensor/_measurements.py
  tests/test_expval.py
  tests/test_measurements.py
  tests/test_serialize.py
Labels: ci:use-multi-gpu-runner

#812 Update `LightningQubit` mid-circuit measurement preprocessing
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  tests/new_api/test_device.py
Labels: ci:build_wheels
