Repository PennyLaneAI/pennylane-lightning, pull requests merged in 2025-10, with the labels that each got.

#1264 Upload Lightning RC wheels for several versions of Python
  .github/CHANGELOG.md
  .github/workflows/set_wheel_build_matrix.yml
  pennylane_lightning/core/_version.py
Labels: ci:build_wheels

#1273 Fix wheels creation for Mac ARM
  .github/CHANGELOG.md
  .github/workflows/wheel_macos_arm64.yml
  pennylane_lightning/core/_version.py
Labels: ci:build_wheels

#1275 PR to RC branch do not upload to TestPyPI
  .github/workflows/wheel_linux_aarch64.yml
  .github/workflows/wheel_linux_aarch64_cuda.yml
  .github/workflows/wheel_linux_x86_64.yml
  .github/workflows/wheel_linux_x86_64_cuda.yml
  .github/workflows/wheel_macos_arm64.yml
  .github/workflows/wheel_macos_x86_64.yml
  .github/workflows/wheel_noarch.yml
  .github/workflows/wheel_win_x86_64.yml
  pennylane_lightning/core/_version.py
  tests/pytest.ini
Labels: ci:use-multi-gpu-runner, ci:build_wheels, ci:use-gpu-runner

#1272 Bump version to v0.44.0-dev
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pyproject.toml
  requirements.txt
  scripts/configure_pyproject_toml.py
Labels: urgent
