Repository PennyLaneAI/pennylane-lightning, pull requests merged in 2025-01, with the labels that each got.

#1025 Add Python CUDA dependencies as Lightning-GPU and Lightning-Tensor wheel dependencies
  .github/CHANGELOG.md
  .github/workflows/tests_lgpumpi_cpp.yml
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/simulators/lightning_gpu/CMakeLists.txt
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/CMakeLists.txt
  requirements-dev.txt
  scripts/configure_pyproject_toml.py
Labels: ci:use-multi-gpu-runner, ci:build_wheels, ci:use-gpu-runner

#1031 Automate aarch64-cuda-wheels tests
  .github/CHANGELOG.md
  .github/workflows/wheel_linux_aarch64_cuda.yml
  CMakeLists.txt
  pennylane_lightning/core/_version.py
  tests/lightning_tensor/test_measurements_class.py
Labels: ci:build_wheels, urgent, ci:use-gpu-runner

#1035 QA docs
  .github/CHANGELOG.md
  README.rst
  doc/lightning_gpu/device.rst
  doc/lightning_kokkos/device.rst
  doc/lightning_qubit/device.rst
  doc/lightning_tensor/device.rst
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_tensor/_measurements.py
  pennylane_lightning/lightning_tensor/_tensornet.py
  pennylane_lightning/lightning_tensor/lightning_tensor.py
Labels: urgent

#1038 Merge v0.40.0_rc to master
  .github/CHANGELOG.md
  .github/workflows/compat-docker-release.yml
  .github/workflows/compat-docker-stable.yml
  .github/workflows/wheel_linux_aarch64_cuda.yml
  CMakeLists.txt
  README.rst
  doc/lightning_gpu/device.rst
  doc/lightning_kokkos/device.rst
  doc/lightning_qubit/device.rst
  doc/lightning_tensor/device.rst
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_tensor/_measurements.py
  pennylane_lightning/lightning_tensor/_tensornet.py
  pennylane_lightning/lightning_tensor/lightning_tensor.py
  scripts/create_lightning_rc.sh
  tests/lightning_tensor/test_measurements_class.py
Labels: ci:use-multi-gpu-runner, ci:build_wheels, ci:use-gpu-runner

#1033 Upgrade minimum required version of Pennylane to v0.40
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/lightning_base.py
  pyproject.toml
  requirements.txt
  scripts/configure_pyproject_toml.py
Labels: ci:build_wheels

#731 SX gate on lightning devices
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/src/gates/Constant.hpp
  pennylane_lightning/core/src/gates/GateOperation.hpp
  pennylane_lightning/core/src/gates/Gates.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/StateVectorCudaBase.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/StateVectorCudaMPI.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/StateVectorCudaManaged.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/gates/cuGateCache.hpp
  pennylane_lightning/core/src/simulators/lightning_gpu/gates/tests/Test_StateVectorCudaManaged_NonParam.cpp
  pennylane_lightning/core/src/simulators/lightning_gpu/gates/tests/mpi/Test_StateVectorCudaMPI_NonParam.cpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/BasicGateFunctors.hpp
  pennylane_lightning/core/src/simulators/lightning_kokkos/gates/tests/Test_StateVectorKokkos_NonParam.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/gates/AssignKernelMap_Default.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/gates/OpToMemberFuncPtr.hpp
  pennylane_lightning/core/src/simulators/lightning_qubit/gates/cpu_kernels/GateImplementationsLM.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/gates/cpu_kernels/GateImplementationsLM.hpp
  pennylane_lightning/core/src/simulators/lightning_qubit/gates/tests/Test_GateImplementations_Nonparam.cpp
  pennylane_lightning/core/src/simulators/lightning_qubit/gates/tests/Test_OpToMemberFuncPtr.cpp
  pennylane_lightning/core/src/simulators/lightning_tensor/tncuda/gates/tests/Test_TNCuda_NonParam.cpp
  pennylane_lightning/core/src/utils/cuda_utils/cuGates_host.hpp
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_gpu/lightning_gpu.toml
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.toml
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  pennylane_lightning/lightning_qubit/lightning_qubit.toml
  tests/test_gates.py
Labels: ci:use-multi-gpu-runner, ci:build_wheels, ci:use-gpu-runner

#1056 Update qemu to fix aarch64 wheel action
  .github/CHANGELOG.md
  .github/workflows/wheel_linux_aarch64.yml
  pennylane_lightning/core/_version.py
Labels: ci:build_wheels

#1059 Update black version
  .github/CHANGELOG.md
  .pre-commit-config.yaml
  README.rst
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_tensor/lightning_tensor.py
  requirements-dev.txt
  requirements.txt
  tests/lightning_tensor/test_serialize_tensor.py
  tests/test_serialize.py
Labels: ci:use-gpu-runner

#1048 Remove unnecessary adjoint pytest skip for Lightning Kokkos
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  tests/test_adjoint_jacobian.py
Labels: ci:use-gpu-runner
