Repository PennyLaneAI/pennylane-lightning, pull requests merged in 2025-04, with the labels that each got.

#1112 Update GPU devices wheels recipes and fix the missing pytest-split in stable/stable
  .github/CHANGELOG.md
  .github/workflows/set_wheel_build_matrix.yml
  .github/workflows/tests_gpu_python.yml
  .github/workflows/tests_linux_cpp.yml
  .github/workflows/tests_lkcpu_python.yml
  .github/workflows/tests_lkcuda_cpp.yml
  .github/workflows/tests_lkcuda_python.yml
  .github/workflows/tests_lqcpu_python.yml
  .github/workflows/wheel_linux_aarch64.yml
  .github/workflows/wheel_linux_aarch64_cuda.yml
  .github/workflows/wheel_linux_x86_64_cuda.yml
  pennylane_lightning/core/_version.py
Labels: ci:use-multi-gpu-runner, ci:build_wheels, ci:use-gpu-runner

#1118 Install Pytorch 2.5.1 CPU in CIs and Update make python command
  .github/workflows/tests_lkcpu_python.yml
  .github/workflows/tests_lkcuda_python.yml
  .github/workflows/tests_lqcpu_python.yml
  Makefile
  pennylane_lightning/core/_version.py
Labels: ci:use-gpu-runner

#1120 Fix decomposition of controlled SProd operators
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_qubit/_state_vector.py
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  pennylane_lightning/lightning_tensor/lightning_tensor.py
  tests/lightning_base/test_device.py
  tests/test_gates.py
  tests/test_templates.py
Labels: ci:use-gpu-runner

#1117 Update changelog
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/lightning_base.py
  pennylane_lightning/lightning_tensor/lightning_tensor.py
Labels: ci:build_wheels, ci:use-gpu-runner

#1128 Remove PSWAP from matrix ops in LK and LGPU
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
Labels: ci:use-multi-gpu-runner, urgent, ci:use-gpu-runner

#1125 Create v0.41.0 Doc branch
  .github/CHANGELOG.md
  README.rst
  doc/lightning_gpu/device.rst
  doc/lightning_kokkos/device.rst
  doc/lightning_qubit/device.rst
  pennylane_lightning/core/_version.py
Labels: do not merge, urgent

#1139 Add header image (PL logo + title) to README
  .github/CHANGELOG.md
  README.rst
  doc/_static/readme/pl-lightning-logo-darkmode.png
  doc/_static/readme/pl-lightning-logo-lightmode.png
  pennylane_lightning/core/_version.py
Labels: documentation
