Repository PennyLaneAI/pennylane-lightning, pull requests merged in 2025-07, with the labels that each got.

#1193 Adhere to PyPA binary distribution format for built wheels
  .github/CHANGELOG.md
  .gitignore
  pennylane_lightning/core/_version.py
  pyproject.toml
  scripts/configure_pyproject_toml.py
  setup.py
Labels: ci:build_wheels

#1194 Fix Lightning Kokkos CUDA test failure with RelWithDebugInfo due to Kokkos Lambda
  .github/CHANGELOG.md
  .github/workflows/tests_lkcuda_cpp.yml
  .github/workflows/tests_lkmpi_cuda_cpp.yml
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/simulators/lightning_kokkos/gates/BasicGateFunctors.hpp
Labels: ci:use-multi-gpu-runner, ci:use-gpu-runner

#1199 Prepare `CHANGELOG.md` for the release 0.42.0
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  scripts/compare_changelog_commits.sh
Labels: documentation

#1187 [nanobind] Improve `probs` and `sample` to make use of zero-copy exchanges
  .github/CHANGELOG.md
  pennylane_lightning/core/bindings/BindingsMPI_nb.hpp
  pennylane_lightning/core/bindings/BindingsUtils_nb.hpp
  pennylane_lightning/core/bindings/Bindings_nb.hpp
Labels: ci:use-multi-gpu-runner, ci:build_wheels, ci:use-gpu-runner

#1189 [nanobind] Feature/nanobind mpi and adj jac base bindings
  .github/CHANGELOG.md
  pennylane_lightning/core/algorithms/AdjointJacobianBase.hpp
  pennylane_lightning/core/bindings/BindingsMPI_nb.hpp
  pennylane_lightning/core/bindings/BindingsUtils_nb.hpp
  pennylane_lightning/core/bindings/Bindings_nb.cpp
  pennylane_lightning/core/bindings/Bindings_nb.hpp
  pennylane_lightning/core/simulators/lightning_gpu/algorithms/AdjointJacobianGPU.hpp
  pennylane_lightning/core/simulators/lightning_gpu/algorithms/AdjointJacobianGPUMPI.hpp
  pennylane_lightning/core/simulators/lightning_kokkos/algorithms/AdjointJacobianKokkos.hpp
  pennylane_lightning/core/simulators/lightning_kokkos/algorithms/AdjointJacobianKokkosMPI.hpp
  pennylane_lightning/core/simulators/lightning_qubit/algorithms/AdjointJacobianLQubit.hpp
  pennylane_lightning/core/simulators/lightning_qubit/bindings/LQubitBindings_nb.hpp
  tests/bindings/test_adjoint_jacobian_nb.py
  tests/bindings/test_bindings_mpi_nb.py
  tests/bindings/test_jax_compatibility_nb.py
Labels: ci:use-multi-gpu-runner, ci:build_wheels, ci:use-gpu-runner

#1202 Create v0.42.0 Doc branch
  .github/CHANGELOG.md
  README.md
  doc/index.rst
  doc/lightning_gpu/installation.rst
  doc/lightning_kokkos/installation.rst
  doc/lightning_kokkos/installation_hpc.rst
  doc/lightning_qubit/installation.rst
  doc/lightning_tensor/installation.rst
  pennylane_lightning/core/_version.py
Labels: documentation, do not merge

#1207 Update pytest version
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  requirements-dev.txt
  requirements-tests.txt
  requirements.txt
Labels: bug, bug-fix

#1211 Remove FIXMEs for pinning jax & catalyst version for CI with stable
  .github/CHANGELOG.md
  .github/workflows/tests_gpu_cpp.yml
  .github/workflows/tests_gpu_python.yml
  .github/workflows/tests_lgpumpi_cpp.yml
  .github/workflows/tests_lgpumpi_python.yml
  .github/workflows/tests_linux_cpp.yml
  .github/workflows/tests_lkcpu_python.yml
  .github/workflows/tests_lkcuda_cpp.yml
  .github/workflows/tests_lkcuda_python.yml
  .github/workflows/tests_lkmpi_cuda_cpp.yml
  .github/workflows/tests_lkmpi_cuda_python.yml
  .github/workflows/tests_lqcpu_python.yml
  .github/workflows/tests_windows_cpp.yml
  .github/workflows/tests_without_binary.yml
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_base/lightning_base.py
Labels: ci:use-multi-gpu-runner, urgent, ci:use-gpu-runner

#1210 Add "device" as a supported MCM method that resolves to "tree-traversal"
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_gpu/lightning_gpu.toml
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.toml
  pennylane_lightning/lightning_qubit/lightning_qubit.py
  pennylane_lightning/lightning_qubit/lightning_qubit.toml
  tests/test_native_mcm.py
Labels: ci:use-gpu-runner

#1184 [nanobind] Implement bindings for Lightning GPU
  .github/CHANGELOG.md
  CMakeLists.txt
  mpitests/conftest.py
  mpitests/test_adjoint_jacobian.py
  pennylane_lightning/core/bindings/BindingsCudaUtils_nb.hpp
  pennylane_lightning/core/bindings/BindingsMPI_nb.hpp
  pennylane_lightning/core/bindings/BindingsUtils_nb.hpp
  pennylane_lightning/core/bindings/Bindings_nb.cpp
  pennylane_lightning/core/bindings/Bindings_nb.hpp
  pennylane_lightning/core/simulators/lightning_gpu/StateVectorCudaBase.hpp
  pennylane_lightning/core/simulators/lightning_gpu/StateVectorCudaManaged.hpp
  pennylane_lightning/core/simulators/lightning_gpu/bindings/LGPUBindings_nb.hpp
  pennylane_lightning/core/simulators/lightning_kokkos/bindings/LKokkosBindings_nb.hpp
  pennylane_lightning/core/simulators/lightning_qubit/bindings/LQubitBindings_nb.hpp
  pennylane_lightning/core/simulators/lightning_tensor/tncuda/bindings/LTensorTNCudaBindings_nb.hpp
  pennylane_lightning/lightning_base/_serialize.py
  pennylane_lightning/lightning_gpu/_adjoint_jacobian.py
  pennylane_lightning/lightning_gpu/_measurements.py
  pennylane_lightning/lightning_gpu/_state_vector.py
  pennylane_lightning/lightning_gpu/lightning_gpu.py
  pennylane_lightning/lightning_qubit/_adjoint_jacobian.py
  tests/bindings/test_bindings_nb.py
  tests/bindings/test_measurements_nb.py
  tests/bindings/test_statevector_nb.py
  tests/conftest.py
  tests/lightning_base/test_expval.py
  tests/lightning_tensor/test_lightning_tensor.py
  tests/test_adjoint_jacobian.py
  tests/test_device.py
  tests/test_measurements.py
  tests/test_serialize.py
  tests/test_vjp.py
Labels: ci:build_wheels, ci:use-gpu-runner

#1213 [nanobind] Kokkos Nanobindings
  .github/CHANGELOG.md
  .github/workflows/tests_lgpumpi_python.yml
  .github/workflows/tests_lkmpi_cuda_python.yml
  Makefile
  pennylane_lightning/core/bindings/BindingsCudaUtils_nb.hpp
  pennylane_lightning/core/bindings/BindingsMPI_nb.hpp
  pennylane_lightning/core/bindings/BindingsUtils_nb.hpp
  pennylane_lightning/core/bindings/Bindings_nb.hpp
  pennylane_lightning/core/simulators/lightning_gpu/bindings/LGPUBindings_nb.hpp
  pennylane_lightning/core/simulators/lightning_kokkos/bindings/LKokkosBindingsMPI_nb.hpp
  pennylane_lightning/core/simulators/lightning_kokkos/bindings/LKokkosBindings_nb.hpp
  pennylane_lightning/core/simulators/lightning_qubit/bindings/LQubitBindings_nb.hpp
  pennylane_lightning/core/utils/Util.hpp
  pennylane_lightning/lightning_base/_serialize.py
  pennylane_lightning/lightning_gpu/_adjoint_jacobian.py
  pennylane_lightning/lightning_gpu/_measurements.py
  pennylane_lightning/lightning_gpu/_mpi_handler.py
  pennylane_lightning/lightning_gpu/_state_vector.py
  pennylane_lightning/lightning_kokkos/_adjoint_jacobian.py
  pennylane_lightning/lightning_kokkos/_measurements.py
  pennylane_lightning/lightning_kokkos/_state_vector.py
  pennylane_lightning/lightning_kokkos/lightning_kokkos.py
  tests/bindings/test_backend_nb.py
  tests/bindings/test_jax_compatibility_nb.py
  tests/bindings/test_measurements_nb.py
  tests/bindings/test_statevector_nb.py
  tests/conftest.py
  tests/lightning_base/test_adjoint_jacobian_class.py
  tests/lightning_base/test_device.py
  tests/lightning_base/test_state_vector_class.py
  tests/test_adjoint_jacobian.py
  tests/test_binary_info.py
  tests/test_serialize.py
Labels: ci:build_wheels, ci:use-gpu-runner

#1205 GPhase support with zero-qubit Lightning devices
  .github/CHANGELOG.md
  pennylane_lightning/core/_version.py
  pennylane_lightning/core/simulators/lightning_kokkos/gates/BasicGateFunctors.hpp
  pennylane_lightning/core/simulators/lightning_kokkos/gates/tests/Test_StateVectorKokkos_Param.cpp
  pennylane_lightning/core/simulators/lightning_qubit/gates/cpu_kernels/GateImplementationsLM.hpp
  pennylane_lightning/core/simulators/lightning_qubit/gates/tests/Test_GateImplementations_Param.cpp
  tests/test_device.py
  tests/test_gates.py
Labels: ci:use-gpu-runner
